window.MERUVA_LANG = {

/* ════════════════════════════════════════
   TIẾNG VIỆT
   ════════════════════════════════════════ */
vi: {
  nav_home: 'Trang chủ',
  nav_eco: 'Hệ sinh thái',
  nav_story: 'Câu chuyện',
  nav_partners: 'Đối tác',
  nav_contact: 'Liên hệ',

  hero_eyebrow: 'Hệ sinh thái cá nhân · Ho Chi Minh City',
  hero_title1: 'Từ đỉnh cao',
  hero_title_em: 'chúng tôi<br>phục vụ.',
  hero_subline: '"From the summit, we serve." — MERUVA · Est. 2026',
  hero_desc: 'Hệ sinh thái được xây dựng bởi Bin — người trở về từ Nhật với tinh thần phục vụ thật. Không "ngáo". Không buzzword. Chỉ làm thật.',
  hero_btn1: 'Khám phá hệ sinh thái',
  hero_btn2: 'Câu chuyện',
  stat1_label: 'Hệ sinh thái',
  stat2_label: 'Tư vấn cá nhân',
  stat3_label: 'Tiếng Nhật · Tư duy quốc tế',
  stat4_label: 'Bánh nướng mỗi sáng',

  eco_label: 'Hệ sinh thái',
  eco_title1: 'Sáu nhánh.',
  eco_title2: 'Một tinh thần.',
  eco_intro: 'Mỗi sub-brand là một cách khác nhau để phục vụ — tư vấn cá nhân, in 3D, café, bánh artisan, cho thuê studio, và thẻ thành viên kết nối toàn hệ thống.',
  eco_explore: 'Khám phá',

  story_label: 'Câu chuyện',
  story_title1: 'Đỉnh núi',
  story_title2: 'không phải',
  story_title3: 'để ngắm.',
  story_desc1: 'MERUVA lấy cảm hứng từ "Meru" — núi thiêng trong văn hóa Á Đông. Không phải để chinh phục. Để từ đỉnh cao đó, phục vụ con người thật sự.',
  story_desc2: 'Bin về từ Nhật với 5 năm quan sát tinh thần phục vụ — <em style="color:var(--gold)">omotenashi</em>. Không nói nhiều. Làm thật.',
  val1_title: 'Serve First',
  val1_desc: 'Phục vụ trước, bán sau. Mỗi sản phẩm là một hành động tử tế.',
  val2_title: 'Summit Quality',
  val2_desc: 'Không thỏa hiệp. Đỉnh núi không có chỗ cho "tạm được".',
  val3_title: 'Honest Craft',
  val3_desc: 'Minh bạch về nguyên liệu, quy trình, giá thành. Không "ngáo".',
  card1_label: 'Brand Tagline',
  card1_quote: '"From the summit, we serve."',
  card2_label: 'Tầm nhìn',
  card2_quote: '"Hệ sinh thái cá nhân được yêu mến vì chất lượng, sự tử tế, và tinh thần phục vụ thật."',
  card3_label: 'Brand Personality',
  card3_quote: '"~28 tuổi, du học về, hiểu chuẩn quốc tế nhưng vẫn giữ chất Việt. Nói ít làm nhiều. Cười dễ."',

  partners_label: 'Đối tác liên kết',
  partners_title1: 'Cùng xây',
  partners_title2: 'hệ sinh thái.',

  contact_label: 'Liên hệ',
  contact_title1: 'Nói chuyện',
  contact_title2: 'thật.',
  ci_hours_label: 'Giờ phục vụ',
  ci_hours_val: 'Mỗi ngày · 7:00 → 22:00',
  form_name_label: 'Tên của bạn',
  form_email_label: 'Email',
  form_msg_label: 'Bạn muốn nói gì',
  form_msg_ph: 'Ghé MERUVA · hợp tác · đặt lịch tư vấn...',
  form_submit: 'Gửi tin nhắn',
  form_thank: 'Cảm ơn bạn! MERUVA sẽ phản hồi sớm ☕',

  footer_eco: 'Hệ sinh thái',
  footer_story: 'Câu chuyện',
  footer_contact: 'Liên hệ',
  footer_copy: '© 2026 MERUVA · Brand Book v1.0',

  sp_back: '← Quay lại',
  sp_from: 'Bắt đầu từ',
  sp_products_label: 'Sản phẩm · Dịch vụ',
  sp_cta_suffix: ' — phục vụ theo đúng nghĩa."',

  pm_offers_label: 'Ưu đãi dành cho MERUVA Card',
  pm_footer_note: 'MERUVA · Đối tác liên kết',
  pm_cta: 'Liên hệ đối tác →',
  pm_detail: 'Xem chi tiết ↗',
  coming_soon: 'Coming Soon',

  stay_eyebrow: 'Summit Living · 654A Quang Trung, Gò Vấp',
  stay_title_em: 'Sống tốt.',
  stay_title2: 'Từ đỉnh cao.',
  stay_coming: 'Dự kiến hoàn thiện · Tháng 09 / 2026',
  stay_desc: 'Studio khép kín mặt tiền Quang Trung, Gò Vấp. Thiết kế tinh gọn, đầy đủ tiện nghi, an ninh tốt. 3 loại diện tích phù hợp mọi nhu cầu.',
  stay_price_badge: '🏠 Bảng giá · 3 loại phòng',
  stay_per_month: '/tháng',
  stay_early_bird: '✦ Đặt giữ chỗ trước tháng 09/2026 — nhận ưu đãi đặc biệt',
  stay_cta: 'Đặt giữ chỗ ngay →',
  stay_loc_label: 'Vị trí',
  stay_loc_val: '654A Quang Trung',
  stay_loc_sub: 'Phường 11 · Gò Vấp · TP.HCM',
  stay_type_label: 'Loại phòng',
  stay_type_val: 'Studio khép kín',
  stay_type_sub: '1 phòng ngủ · bếp · WC riêng',
  stay_area_label: 'Diện tích',
  stay_area_val: '17 · 21 · 24m²',
  stay_area_sub: '3 loại · 9 căn tổng cộng',
  stay_rent_label: 'Giá thuê',
  stay_rent_val: 'Từ 5.500.000₫',
  stay_rent_sub: '/tháng · 3 mức giá',
  stay_floor_label: 'Cấu trúc toà nhà',
  stay_floor_t1: '9 studio.',
  stay_floor_t2: '3 tầng.',
  stay_floor_hint: '↓ Nhấn vào sơ đồ để khám phá từng tầng',
  stay_types_label: 'Loại studio',
  stay_types_t1: 'Chọn không gian',
  stay_types_t2: 'phù hợp bạn.',
  stay_popular: 'Phổ biến',
  stay_rent_card: 'Giá thuê',
  stay_book_now: 'Đặt ngay',
  roomA_name:'Phòng A', roomA_li1:'Phòng ngủ + bếp mini + WC riêng', roomA_li2:'Bố cục tinh gọn, tối ưu công năng', roomA_li3:'Phù hợp 1 người · sinh viên · đi làm', roomA_li4:'Cửa sổ lấy sáng tự nhiên', roomA_avail:'3 căn · Lầu 1 / 2 / 3',
  roomB_name:'Phòng B', roomB_li1:'Phòng ngủ + bếp + WC riêng', roomB_li2:'Diện tích hợp lý, đầy đủ công năng', roomB_li3:'Phù hợp 1–2 người', roomB_li4:'Bàn làm việc · tủ quần áo đầy đủ', roomB_avail:'3 căn · Lầu 1 / 2 / 3',
  roomC_name:'Phòng C', roomC_li1:'Phòng ngủ rộng + bếp + WC riêng', roomC_li2:'Không gian thoáng đãng nhất', roomC_li3:'Phù hợp couple · 1–2 người', roomC_li4:'Góc làm việc riêng · tủ lớn hơn', roomC_avail:'3 căn · Lầu 1 / 2 / 3',
  stay_amenities_label: 'Tiện ích',
  stay_amenities_t1: 'Đầy đủ.',
  stay_amenities_t2: 'Không thiếu gì.',
  amenity1:'Máy lạnh', amenity2:'Nóng lạnh', amenity3:'Bếp điện từ', amenity4:'Tủ lạnh', amenity5:'Giường · Nệm', amenity6:'Tủ quần áo', amenity7:'Bàn làm việc', amenity8:'Wifi tốc độ cao', amenity9:'Camera an ninh', amenity10:'Chỗ để xe',
  stay_loc_sec_label: 'Vị trí',
  stay_loc_t1: 'Mặt tiền lớn.',
  stay_loc_t2: 'Tiện di chuyển.',
  loc1_title:'Mặt tiền đường Quang Trung', loc1_desc:'654A, P.11, Gò Vấp — đường lớn, dễ tìm, tiện di chuyển',
  loc2_title:'Tiện ăn uống & mua sắm', loc2_desc:'Gần chợ Gò Vấp, siêu thị, quán ăn đa dạng xung quanh',
  loc3_title:'Kết nối trung tâm dễ dàng', loc3_desc:'Cách Q.1 khoảng 20–25 phút · kết nối Q.12, Bình Thạnh, Tân Bình',
  loc4_title:'Gần khu giáo dục & y tế', loc4_desc:'Phù hợp sinh viên, người đi làm khu vực Gò Vấp – Bình Thạnh',
  loc5_title:'An ninh khu dân cư', loc5_desc:'Khu dân cư đông đúc, camera toà nhà, khoá cửa riêng từng phòng',
  map_note: 'Google Maps · Sẽ được cập nhật',
  stay_process_label: 'Quy trình',
  stay_process_t1: '5 bước',
  stay_process_t2: 'nhận phòng.',
  step1_t:'Điền form', step1_n:'Điền thông tin đặt giữ chỗ bên dưới',
  step2_t:'Tư vấn', step2_n:'MERUVA liên hệ trong vòng 24h làm việc',
  step3_t:'Đặt cọc', step3_n:'Cọc 1 tháng tiền thuê để giữ chỗ',
  step4_t:'Ký hợp đồng', step4_n:'Ký khi hoàn thiện · Tháng 09/2026',
  step5_t:'Nhận phòng', step5_n:'Bắt đầu cuộc sống tại MERUVA Stay',
  stay_form_label: 'Đặt giữ chỗ',
  stay_form_t1: 'Điền thông tin.',
  stay_form_t2: 'MERUVA liên hệ trong 24h.',
  sf_name:'Họ và tên', sf_name_ph:'Nguyễn Văn A',
  sf_phone:'Số điện thoại / Zalo', sf_phone_ph:'0912 345 678',
  sf_email:'Email',
  sf_room:'Loại studio quan tâm',
  sf_room_default:'— Chọn loại phòng —',
  sf_room_opt1:'Phòng A · 17m² · 5.500.000₫/tháng',
  sf_room_opt2:'Phòng B · 21m² · 6.000.000₫/tháng',
  sf_room_opt3:'Phòng C · 24m² · 6.500.000₫/tháng',
  sf_room_opt4:'Chưa quyết định · cần tư vấn thêm',
  sf_people:'Số người ở', sf_people_default:'— Chọn —', sf_people_1:'1 người', sf_people_2:'2 người',
  sf_movein:'Thời gian muốn nhận phòng', sf_movein_default:'— Chọn —',
  sf_movein_1:'Tháng 09/2026 (sớm nhất)', sf_movein_2:'Tháng 10/2026', sf_movein_3:'Tháng 11/2026 trở đi',
  sf_note:'Ghi chú thêm', sf_note_ph:'Yêu cầu đặc biệt, câu hỏi thêm...',
  sf_send:'Gửi đăng ký →',
  sf_thank:'Cảm ơn bạn đã đặt giữ chỗ!\nMERUVA sẽ liên hệ trong vòng 24h ☕',
  stay_faq_label: 'Câu hỏi thường gặp',
  stay_faq_t1: 'Hỏi &',
  stay_faq_t2: 'Đáp.',
  faq1_q:'Cọc bao nhiêu để giữ chỗ?',
  faq1_a:'Cọc 1 tháng tiền thuê để giữ chỗ (5.500.000₫ · 6.000.000₫ · hoặc 6.500.000₫ tùy loại phòng). Khoản cọc được tính vào tháng đầu tiên khi nhận phòng. Hoàn cọc 100% nếu hủy trước ngày nhận phòng 30 ngày.',
  faq2_q:'Nếu công trình trễ tiến độ thì sao?',
  faq2_a:'MERUVA sẽ thông báo sớm nếu có thay đổi tiến độ. Khách đặt giữ chỗ có quyền hoàn cọc toàn bộ 100% hoặc tiếp tục chờ — không phát sinh bất kỳ chi phí nào.',
  faq3_q:'Có nuôi thú cưng được không?',
  faq3_a:'Hiện tại MERUVA Stay chưa hỗ trợ nuôi thú cưng trong giai đoạn đầu. Chính sách có thể được cập nhật sau khi toà nhà đi vào hoạt động và lấy ý kiến cư dân.',
  faq4_q:'Có ký hợp đồng dài hạn được không?',
  faq4_a:'Hợp đồng tối thiểu 3 tháng. Hợp đồng 6 tháng giảm thêm 3%, hợp đồng 1 năm giảm thêm 5% so với giá ưu đãi. Liên hệ MERUVA để được tư vấn phương án phù hợp nhất.',
  faq5_q:'Thanh toán theo tháng, quý hay năm?',
  faq5_a:'Hỗ trợ cả 3 hình thức. Thanh toán theo tháng (bình thường), theo quý giảm thêm 3%, theo năm giảm thêm 5% — áp dụng trên mức giá ưu đãi đặt trước.',

  ecosystem: [
    { id:'service', num:'01', name:'MERUVA Service', shortName:'Service', sub:'Trust Blue · Bespoke', tagline:'Tư vấn hệ thống cá nhân',
      desc:'Bin trực tiếp dẫn dắt 1:1. Từ tư duy đến hệ thống — Notion, Calendar, workflow, automation. Mỗi session là một bước leo núi.',
      heroTagline:'Xây hệ thống —\nleo đỉnh.',
      heroDesc:'Bin tư vấn 1:1 về hệ thống cá nhân, workflow & automation. Tư duy nhập từ Nhật, áp dụng thực tế Việt Nam. Không template. Không copy-paste.',
      fromPrice:'300.000₫', ctaText:'Đặt lịch tư vấn', loaderSub:'Personal System · Bespoke · 1:1',
      products:[{name:'Tư vấn định hướng cá nhân',note:'60 phút · career & lifestyle design',price:'300.000₫'},{name:'Tư vấn hệ thống cá nhân',note:'1:1 · 90 phút · online / offline',price:'500.000₫'},{name:'Setup workflow cá nhân',note:'Notion · Calendar · automation · full setup',price:'1.500.000₫'},{name:'Dự án doanh nghiệp',note:'Quote theo scope · liên hệ trực tiếp',price:'Liên hệ'}],
      tag:'Bespoke · Made for you' },
    { id:'print3d', num:'02', name:'MERUVA 3D', shortName:'3D', sub:'Craft Series · Custom', tagline:'In 3D theo yêu cầu',
      desc:'Từ file thiết kế đến sản phẩm thực tế — PLA, PETG, resin. Móc khóa, figure, vật phẩm sự kiện, mô hình kỹ thuật. Không giới hạn sáng tạo.',
      heroTagline:'Thiết kế.\nIn thật.',
      heroDesc:'MERUVA 3D biến file của bạn thành vật thể thực tế. PLA, PETG, resin cao cấp. Từ quà tặng cá nhân đến sản phẩm sự kiện doanh nghiệp — giao trong 3–5 ngày.',
      fromPrice:'Từ 80.000₫', ctaText:'Đặt in ngay', loaderSub:'3D Printing · Custom · On-demand',
      products:[{name:'In 3D theo file (PLA/PETG)',note:'Upload file STL · giao 3–5 ngày làm việc',price:'Từ 150.000₫'},{name:'In resin cao cấp',note:'Chi tiết sắc nét · màu sắc đa dạng',price:'Từ 250.000₫'},{name:'Móc khóa custom',note:'PLA · đủ màu · phù hợp số lượng lớn',price:'Từ 80.000₫'},{name:'Figure & mô hình',note:'Anime · character · bust · tỷ lệ 1:12',price:'Từ 300.000₫'},{name:'Vật phẩm sự kiện / corporate gift',note:'Custom logo · đóng gói riêng · số lượng lớn',price:'Từ 120.000₫'},{name:'Dự án doanh nghiệp',note:'Nguyên mẫu kỹ thuật · hàng loạt · quote theo scope',price:'Liên hệ'}],
      tag:'On-demand · 3–5 ngày' },
    { id:'bakery', num:'03', name:'MERUVA Bakery', shortName:'Bakery', sub:'Cream Serve · Artisan', tagline:'Bánh nướng mỗi sáng',
      desc:'Croissant lớp giòn, sourdough lên men 36h, bánh ngọt artisan. Nướng lúc 7h — hết là hết, không hâm nóng.',
      heroTagline:'Nướng lúc 7h.\nHết là hết.',
      heroDesc:'Không hâm nóng. Không nhượng bộ chất lượng. Mỗi chiếc bánh là một cam kết — bơ Pháp, bột nguyên cám, men tự nhiên.',
      fromPrice:'45.000₫', ctaText:'Đặt bánh', loaderSub:'Artisan Bakery · Fresh Daily · 7:00',
      products:[{name:'Croissant Butter',note:'Bơ Pháp · lớp giòn · freshly baked',price:'45.000₫'},{name:'Pain au Chocolat',note:'Sô-cô-la 70% Bỉ · warm',price:'55.000₫'},{name:'Sourdough 36h',note:'Nguyên cám · lên men tự nhiên · ổ 500g',price:'120.000₫'},{name:'Cinnamon Roll',note:'Quế Tích Lan · cream cheese frosting',price:'65.000₫'},{name:'Kouign-Amann',note:'Caramel giòn · bơ mặn',price:'70.000₫'},{name:'Bánh kem đặt riêng',note:'Custom design · báo trước 48h',price:'Từ 450.000₫'}],
      tag:'Fresh daily · Hết là hết' },
    { id:'coffee', num:'04', name:'MERUVA Coffee', shortName:'Coffee', sub:'Summit Gold · Specialty', tagline:'Cà phê rang xay đặc sản',
      desc:'Hạt tuyển chọn từ Đà Lạt, rang chậm từng mẻ nhỏ. Espresso chuẩn Ý, pour-over theo gu từng người.',
      heroTagline:'Rang chậm.\nUống thật.',
      heroDesc:'Hạt Đà Lạt được tuyển tay. Rang chậm theo từng mẻ nhỏ. Pha theo kỹ thuật — không phải công thức.',
      fromPrice:'45.000₫', ctaText:'Xem menu', loaderSub:'Specialty Coffee · Đà Lạt Origin',
      products:[{name:'Summit Espresso',note:'Single origin · house blend · 30ml',price:'45.000₫'},{name:'Pour-over Đà Lạt',note:'V60 · hand-brew · 200ml',price:'65.000₫'},{name:'Cappuccino Cream',note:'Double shot · sữa tươi nguyên kem',price:'55.000₫'},{name:'Cold Brew 12h',note:'Slow cold-extracted · 300ml',price:'55.000₫'},{name:'Flat White',note:'Ristretto · micro-foam milk',price:'60.000₫'},{name:'Hạt rang Summit',note:'Túi 250g · medium roast · để pha ở nhà',price:'180.000₫'}],
      tag:'Daily · 7:00 → 22:00' },
    { id:'stay', num:'05', name:'MERUVA Stay', shortName:'Stay', sub:'Summit Living · For Rent', tagline:'Studio cho thuê mặt tiền',
      desc:'9 studio khép kín tại 654A Quang Trung, Gò Vấp. 17m² · 21m² · 24m². Ưu đãi đặt trước.',
      heroTagline:'Sống tốt.\nTừ đỉnh cao.',
      heroDesc:'9 studio khép kín mặt tiền Quang Trung, Gò Vấp. Thiết kế tinh gọn, đầy đủ tiện nghi. Ưu đãi đặt trước — tiết kiệm 12.000.000₫ cho năm đầu tiên.',
      fromPrice:'Từ 5.500.000₫/tháng', ctaText:'Đặt giữ chỗ', loaderSub:'Summit Living · 654A Quang Trung · Gò Vấp',
      customSubPage:true, products:[] },
    { id:'card', num:'06', name:'MERUVA Card', shortName:'Card', sub:'Peak Silver · Membership', tagline:'Thẻ thành viên hệ sinh thái',
      desc:'Một thẻ — mở mọi cánh cửa MERUVA và đối tác liên kết. Tích điểm, ưu đãi, sự kiện riêng.',
      heroTagline:'Một thẻ.\nMọi cánh cửa.',
      heroDesc:'MERUVA Card kết nối bạn với toàn bộ hệ sinh thái — từ coffee đến bakery, tư vấn, và các đối tác liên kết.',
      fromPrice:'Miễn phí', ctaText:'Đăng ký thẻ', loaderSub:'Membership · Ecosystem-wide',
      products:[{name:'Summit Member',note:'Tích điểm · ưu đãi 5% toàn hệ thống',price:'Miễn phí'},{name:'Gold Member',note:'Ưu đãi 10% · ưu tiên đặt bàn · quà sinh nhật',price:'500.000₫/năm'},{name:'Peak Member',note:'Ưu đãi 15% · event riêng · personal barista call',price:'1.500.000₫/năm'},{name:'Gift Card',note:'Mệnh giá tùy chọn · thiệp in tên riêng',price:'Từ 200.000₫'}],
      tag:'Lifetime · Ecosystem-wide' }
  ],

  partners: [
    {name:'Studio Vạn',cat:'Creative · Branding',eyebrow:'Creative Partner',desc:'Studio thiết kế thương hiệu và visual identity tại TP.HCM. Chuyên brand identity, packaging design và content sáng tạo cho các thương hiệu lifestyle.',offers:[{icon:'✦',title:'Tư vấn brand miễn phí 30 phút',note:'Dành riêng cho thành viên MERUVA Card',tag:'Miễn phí'},{icon:'◈',title:'Giảm 10% dịch vụ thiết kế',note:'Áp dụng toàn bộ gói brand identity & packaging',tag:'−10%'},{icon:'▲',title:'Ưu tiên lịch làm việc',note:'Peak Member được xếp lịch trong vòng 48h',tag:'Peak'}]},
    {name:'Atlas Coffee',cat:'Specialty Roaster',eyebrow:'Coffee Partner',desc:'Nhà rang xay specialty hàng đầu — nguồn cung cấp hạt tuyển chọn cho MERUVA Coffee. Từ farm đến tách, mỗi mẻ rang đều có truy xuất nguồn gốc.',offers:[{icon:'✦',title:'Tasting session tại xưởng rang',note:'Tham quan và thử hạt tươi — booking qua MERUVA',tag:'Exclusive'},{icon:'◈',title:'Giảm 8% khi mua hạt trực tiếp',note:'Dành cho thành viên Gold & Peak',tag:'−8%'},{icon:'▲',title:'Workshop rang café hàng tháng',note:'Ưu tiên đăng ký cho MERUVA Card holder',tag:'Monthly'}]},
    {name:'Maison Lụa',cat:'Lifestyle · Decor',eyebrow:'Lifestyle Partner',desc:'Không gian curated lifestyle — từ đồ nội thất nhỏ, đèn decor đến phụ kiện bàn làm việc. Thẩm mỹ Á Đông hiện đại, chọn lọc kỹ càng từng món.',offers:[{icon:'✦',title:'Giảm 12% toàn bộ sản phẩm',note:'Áp dụng cho Gold Member & Peak Member',tag:'−12%'},{icon:'◈',title:'Tư vấn decor không gian làm việc',note:'Kèm theo gói tư vấn hệ thống của MERUVA Service',tag:'Bundle'},{icon:'▲',title:'Quà welcome kit',note:'Tặng kèm khi đăng ký Peak Member mới',tag:'Gift'}]},
    {name:'Nội thất Mộc',cat:'Furniture · Wood',eyebrow:'Craft Partner',desc:'Xưởng mộc thủ công — đồ nội thất từ gỗ tự nhiên FSC, làm theo đặt hàng. Từ bàn làm việc đến kệ sách, mỗi món là một tác phẩm.',offers:[{icon:'✦',title:'Giảm 7% đơn hàng đặt riêng',note:'Áp dụng khi xuất trình MERUVA Card khi đặt',tag:'−7%'},{icon:'◈',title:'Tư vấn thiết kế không gian miễn phí',note:'1 buổi tư vấn 45 phút với thợ mộc chính',tag:'Miễn phí'},{icon:'▲',title:'Khắc tên / logo theo yêu cầu',note:'Miễn phí khắc laser cho Peak Member',tag:'Peak'}]},
    {name:'Florist Hạ',cat:'Floral · Event',eyebrow:'Floral Partner',desc:'Studio hoa tươi artisan — bó hoa theo cảm xúc, setup sự kiện, hoa để bàn định kỳ. Không làm hoa công nghiệp. Mỗi bó là một câu chuyện.',offers:[{icon:'✦',title:'Giảm 10% đơn hoa tươi',note:'Áp dụng tất cả thành viên MERUVA Card',tag:'−10%'},{icon:'◈',title:'Đăng ký hoa bàn định kỳ',note:'Gói tuần / tháng — ưu đãi thêm 5% cho thành viên',tag:'Subscription'},{icon:'▲',title:'Hoa setup sự kiện MERUVA',note:'Florist Hạ là đối tác độc quyền cho sự kiện MERUVA',tag:'Exclusive'}]},
    {name:'Print House',cat:'Print · Stationery',eyebrow:'Print Partner',desc:'Nhà in chuyên nghiệp — card visit, menu, packaging, stationery cao cấp. In offset & kỹ thuật số, chất liệu đặc biệt, hoàn thiện thủ công.',offers:[{icon:'✦',title:'Giảm 10% đơn in đầu tiên',note:'Dành cho thành viên mới xuất trình MERUVA Card',tag:'−10%'},{icon:'◈',title:'Thiết kế template miễn phí',note:'Cho các ấn phẩm chuẩn (card, menu A5, voucher)',tag:'Miễn phí'},{icon:'▲',title:'Giao hàng nhanh 24h',note:'Ưu tiên sản xuất cho Peak Member',tag:'Priority'}]},
    null, null, null, null
  ],

  floorData: {
    4:{label:'Lầu 3',tag:'LẦU 3',desc:'Tầng cao nhất · view thoáng · ít tiếng ồn',rooms:[{n:'Phòng 301 · 21m²',d:'6.000.000₫ / tháng'},{n:'Phòng 302 · 17m²',d:'5.500.000₫ / tháng'},{n:'Phòng 303 · 24m²',d:'6.500.000₫ / tháng'}]},
    3:{label:'Lầu 2',tag:'LẦU 2',desc:'Tầng giữa · cân bằng giữa tiếp cận và riêng tư',rooms:[{n:'Phòng 201 · 21m²',d:'6.000.000₫ / tháng'},{n:'Phòng 202 · 17m²',d:'5.500.000₫ / tháng'},{n:'Phòng 203 · 24m²',d:'6.500.000₫ / tháng'}]},
    2:{label:'Lầu 1',tag:'LẦU 1',desc:'Tiện di chuyển · phù hợp sinh hoạt năng động',rooms:[{n:'Phòng 101 · 21m²',d:'6.000.000₫ / tháng'},{n:'Phòng 102 · 17m²',d:'5.500.000₫ / tháng'},{n:'Phòng 103 · 24m²',d:'6.500.000₫ / tháng'}]},
    1:{label:'Tầng trệt',tag:'TRỆT',desc:'Khu để xe có mái che · dành riêng cho cư dân',rooms:[{n:'Khu để xe',d:'6 vị trí · mái che · dành riêng'},{n:'Lối vào chính',d:'654A Quang Trung · Gò Vấp'}]}
  }
},

/* ════════════════════════════════════════
   ENGLISH
   ════════════════════════════════════════ */
en: {
  nav_home:'Home', nav_eco:'Ecosystem', nav_story:'Story', nav_partners:'Partners', nav_contact:'Contact',
  hero_eyebrow:'Personal Ecosystem · Ho Chi Minh City',
  hero_title1:'From the summit',
  hero_title_em:'we serve.',
  hero_subline:'"From the summit, we serve." — MERUVA · Est. 2026',
  hero_desc:'An ecosystem built by Bin — returned from Japan with a genuine spirit of service. No hype. No buzzwords. Just real work.',
  hero_btn1:'Explore the ecosystem', hero_btn2:'Our story',
  stat1_label:'Ecosystem brands', stat2_label:'Personal consulting', stat3_label:'Japanese · International mindset', stat4_label:'Fresh baked every morning',
  eco_label:'Ecosystem', eco_title1:'Six branches.', eco_title2:'One spirit.',
  eco_intro:'Each sub-brand is a different way to serve — personal consulting, 3D printing, café, artisan bakery, studio rental, and a membership card connecting the whole ecosystem.',
  eco_explore:'Explore',
  story_label:'Story', story_title1:'The summit', story_title2:'is not', story_title3:'for admiring.',
  story_desc1:'MERUVA draws inspiration from "Meru" — the sacred mountain in Asian culture. Not to conquer it. But to serve people genuinely from its peak.',
  story_desc2:'Bin returned from Japan with 5 years observing the spirit of service — <em style="color:var(--gold)">omotenashi</em>. Less talk. Real action.',
  val1_title:'Serve First', val1_desc:'Serve before selling. Every product is an act of kindness.',
  val2_title:'Summit Quality', val2_desc:'No compromise. The summit has no room for "good enough".',
  val3_title:'Honest Craft', val3_desc:'Transparent about ingredients, process, and price. No hype.',
  card1_label:'Brand Tagline', card1_quote:'"From the summit, we serve."',
  card2_label:'Vision', card2_quote:'"A personal ecosystem loved for quality, kindness, and genuine service."',
  card3_label:'Brand Personality', card3_quote:'"~28 years old, studied abroad, understands international standards but keeps the Vietnamese soul. Actions over words. Easy smile."',
  partners_label:'Partner Network', partners_title1:'Building together', partners_title2:'the ecosystem.',
  contact_label:'Contact', contact_title1:"Let's talk", contact_title2:'honestly.',
  ci_hours_label:'Hours', ci_hours_val:'Every day · 7:00 → 22:00',
  form_name_label:'Your name', form_email_label:'Email', form_msg_label:"What's on your mind",
  form_msg_ph:'Visit MERUVA · collaborate · book a consulting session...',
  form_submit:'Send message', form_thank:'Thank you! MERUVA will reply soon ☕',
  footer_eco:'Ecosystem', footer_story:'Story', footer_contact:'Contact', footer_copy:'© 2026 MERUVA · Brand Book v1.0',
  sp_back:'← Back', sp_from:'Starting from', sp_products_label:'Products · Services', sp_cta_suffix:' — service as it should be."',
  pm_offers_label:'Exclusive perks for MERUVA Card holders', pm_footer_note:'MERUVA · Partner Network', pm_cta:'Contact partner →', pm_detail:'View details ↗', coming_soon:'Coming Soon',
  stay_eyebrow:'Summit Living · 654A Quang Trung, Gò Vấp',
  stay_title_em:'Live well.', stay_title2:'From the summit.',
  stay_coming:'Estimated completion · September 2026',
  stay_desc:'Self-contained studios on Quang Trung main road, Gò Vấp. Compact design, full amenities, great security. 3 size options.',
  stay_price_badge:'🏠 Pricing · 3 room types', stay_per_month:'/month',
  stay_early_bird:'✦ Reserve before Sep 2026 — receive a special early-bird offer',
  stay_cta:'Reserve your spot →',
  stay_loc_label:'Location', stay_loc_val:'654A Quang Trung', stay_loc_sub:'Ward 11 · Gò Vấp · Ho Chi Minh City',
  stay_type_label:'Room type', stay_type_val:'Self-contained studio', stay_type_sub:'1 bedroom · kitchen · private bathroom',
  stay_area_label:'Area', stay_area_val:'17 · 21 · 24m²', stay_area_sub:'3 types · 9 units total',
  stay_rent_label:'Rent', stay_rent_val:'From 5,500,000₫', stay_rent_sub:'/month · 3 price tiers',
  stay_floor_label:'Building structure', stay_floor_t1:'9 studios.', stay_floor_t2:'3 floors.',
  stay_floor_hint:'↓ Click the diagram to explore each floor',
  stay_types_label:'Studio types', stay_types_t1:'Choose the space', stay_types_t2:'that suits you.',
  stay_popular:'Most popular', stay_rent_card:'Monthly rent', stay_book_now:'Book now',
  roomA_name:'Room A', roomA_li1:'Bedroom + mini kitchen + private bathroom', roomA_li2:'Compact layout, optimized for function', roomA_li3:'Ideal for 1 person · student · working professional', roomA_li4:'Natural light window', roomA_avail:'3 units · Floor 1 / 2 / 3',
  roomB_name:'Room B', roomB_li1:'Bedroom + kitchen + private bathroom', roomB_li2:'Practical size, fully functional', roomB_li3:'Suitable for 1–2 people', roomB_li4:'Work desk · full wardrobe', roomB_avail:'3 units · Floor 1 / 2 / 3',
  roomC_name:'Room C', roomC_li1:'Spacious bedroom + kitchen + private bathroom', roomC_li2:'Most open and airy layout', roomC_li3:'Suitable for couple · 1–2 people', roomC_li4:'Dedicated work corner · larger wardrobe', roomC_avail:'3 units · Floor 1 / 2 / 3',
  stay_amenities_label:'Amenities', stay_amenities_t1:'Everything included.', stay_amenities_t2:'Nothing missing.',
  amenity1:'Air conditioning', amenity2:'Hot water', amenity3:'Induction cooker', amenity4:'Refrigerator', amenity5:'Bed & mattress', amenity6:'Wardrobe', amenity7:'Work desk', amenity8:'High-speed WiFi', amenity9:'Security cameras', amenity10:'Parking space',
  stay_loc_sec_label:'Location', stay_loc_t1:'Main road frontage.', stay_loc_t2:'Easy to get around.',
  loc1_title:'Quang Trung main road frontage', loc1_desc:'654A, Ward 11, Gò Vấp — major road, easy to find, great connectivity',
  loc2_title:'Food & shopping nearby', loc2_desc:'Near Gò Vấp market, supermarkets, diverse dining options',
  loc3_title:'Easy city center access', loc3_desc:'~20–25 min to District 1 · connects to D.12, Bình Thạnh, Tân Bình',
  loc4_title:'Near education & healthcare', loc4_desc:'Ideal for students and professionals in the Gò Vấp – Bình Thạnh area',
  loc5_title:'Secure residential area', loc5_desc:'Dense neighborhood, building cameras, individual room locks',
  map_note:'Google Maps · Coming soon',
  stay_process_label:'Process', stay_process_t1:'5 steps', stay_process_t2:'to move in.',
  step1_t:'Fill the form', step1_n:'Submit your reservation info below',
  step2_t:'Consultation', step2_n:'MERUVA contacts you within 24 business hours',
  step3_t:'Deposit', step3_n:'1 month deposit to hold your spot',
  step4_t:'Sign contract', step4_n:'Sign when ready · September 2026',
  step5_t:'Move in', step5_n:'Start your life at MERUVA Stay',
  stay_form_label:'Reserve your spot', stay_form_t1:'Fill in your details.', stay_form_t2:'MERUVA will contact you within 24h.',
  sf_name:'Full name', sf_name_ph:'Your name', sf_phone:'Phone / Zalo', sf_phone_ph:'+84 912 345 678', sf_email:'Email',
  sf_room:'Studio type of interest', sf_room_default:'— Select room type —',
  sf_room_opt1:'Room A · 17m² · 5,500,000₫/month', sf_room_opt2:'Room B · 21m² · 6,000,000₫/month', sf_room_opt3:'Room C · 24m² · 6,500,000₫/month', sf_room_opt4:'Undecided · need more advice',
  sf_people:'Number of occupants', sf_people_default:'— Select —', sf_people_1:'1 person', sf_people_2:'2 people',
  sf_movein:'Preferred move-in date', sf_movein_default:'— Select —',
  sf_movein_1:'September 2026 (earliest)', sf_movein_2:'October 2026', sf_movein_3:'November 2026 or later',
  sf_note:'Additional notes', sf_note_ph:'Special requests, questions...',
  sf_send:'Submit reservation →', sf_thank:'Thank you for your reservation!\nMERUVA will be in touch within 24h ☕',
  stay_faq_label:'FAQ', stay_faq_t1:'Questions &', stay_faq_t2:'Answers.',
  faq1_q:'How much deposit to reserve a spot?', faq1_a:'A 1-month deposit (5,500,000₫ · 6,000,000₫ · or 6,500,000₫ depending on room type) is required. This deposit counts toward your first month of rent. Full 100% refund if you cancel at least 30 days before move-in.',
  faq2_q:'What if construction is delayed?', faq2_a:'MERUVA will notify you early if there are any schedule changes. Depositors have the right to a full 100% refund or to continue waiting — no additional charges will apply.',
  faq3_q:'Are pets allowed?', faq3_a:'MERUVA Stay does not currently support pets in the initial phase. The policy may be updated after the building opens and resident feedback is collected.',
  faq4_q:'Can I sign a long-term lease?', faq4_a:'Minimum lease is 3 months. 6-month leases receive an additional 3% discount, 1-year leases receive 5% off the early-bird rate. Contact MERUVA for the best plan for you.',
  faq5_q:'Monthly, quarterly, or annual payment?', faq5_a:'All three options are supported. Monthly (standard), quarterly saves an extra 3%, annually saves 5% — applied on top of the early-bird rate.',

  ecosystem: [
    {id:'service',num:'01',name:'MERUVA Service',shortName:'Service',sub:'Trust Blue · Bespoke',tagline:'Personal system consulting',desc:'Bin leads each session 1:1. From mindset to systems — Notion, Calendar, workflow, automation. Every session is a step up the mountain.',heroTagline:'Build your system —\nreach the summit.',heroDesc:'Bin consults 1:1 on personal systems, workflow & automation. Japanese-informed thinking, applied to Vietnamese reality. No templates. No copy-paste.',fromPrice:'300,000₫',ctaText:'Book a session',loaderSub:'Personal System · Bespoke · 1:1',products:[{name:'Personal direction consultation',note:'60 min · career & lifestyle design',price:'300,000₫'},{name:'Personal system consultation',note:'1:1 · 90 min · online / in-person',price:'500,000₫'},{name:'Personal workflow setup',note:'Notion · Calendar · automation · full setup',price:'1,500,000₫'},{name:'Enterprise project',note:'Quoted by scope · contact directly',price:'Contact'}],tag:'Bespoke · Made for you'},
    {id:'print3d',num:'02',name:'MERUVA 3D',shortName:'3D',sub:'Craft Series · Custom',tagline:'Custom 3D printing',desc:'From design file to physical product — PLA, PETG, resin. Keychains, figures, event items, technical models. Unlimited creativity.',heroTagline:'Design it.\nPrint it real.',heroDesc:'MERUVA 3D turns your files into physical objects. Premium PLA, PETG, and resin. From personal gifts to corporate event items — delivered in 3–5 days.',fromPrice:'From 80,000₫',ctaText:'Order a print',loaderSub:'3D Printing · Custom · On-demand',products:[{name:'3D print from file (PLA/PETG)',note:'Upload STL · delivered in 3–5 business days',price:'From 150,000₫'},{name:'Premium resin print',note:'Sharp detail · wide color range',price:'From 250,000₫'},{name:'Custom keychain',note:'PLA · full color range · bulk-friendly',price:'From 80,000₫'},{name:'Figures & models',note:'Anime · character · bust · 1:12 scale',price:'From 300,000₫'},{name:'Event items / corporate gifts',note:'Custom logo · individual packaging · bulk orders',price:'From 120,000₫'},{name:'Enterprise project',note:'Technical prototypes · batch production · quoted by scope',price:'Contact'}],tag:'On-demand · 3–5 days'},
    {id:'bakery',num:'03',name:'MERUVA Bakery',shortName:'Bakery',sub:'Cream Serve · Artisan',tagline:'Freshly baked every morning',desc:"Flaky croissants, 36h sourdough, artisan pastries. Baked at 7am — when it's gone, it's gone. No reheating.",heroTagline:"Baked at 7am.\nGone is gone.",heroDesc:"No reheating. No compromise on quality. Every piece is a commitment — French butter, whole grain flour, natural yeast.",fromPrice:'45,000₫',ctaText:'Order pastries',loaderSub:'Artisan Bakery · Fresh Daily · 7:00',products:[{name:'Butter Croissant',note:'French butter · flaky layers · freshly baked',price:'45,000₫'},{name:'Pain au Chocolat',note:'70% Belgian chocolate · warm',price:'55,000₫'},{name:'36h Sourdough',note:'Whole grain · natural fermentation · 500g loaf',price:'120,000₫'},{name:'Cinnamon Roll',note:'Ceylon cinnamon · cream cheese frosting',price:'65,000₫'},{name:'Kouign-Amann',note:'Crispy caramel · salted butter',price:'70,000₫'},{name:'Custom cake',note:'Custom design · 48h advance order',price:'From 450,000₫'}],tag:"Fresh daily · Gone is gone"},
    {id:'coffee',num:'04',name:'MERUVA Coffee',shortName:'Coffee',sub:'Summit Gold · Specialty',tagline:'Specialty roasted coffee',desc:'Hand-selected beans from Đà Lạt, slow-roasted in small batches. Proper espresso, pour-over tailored to each guest.',heroTagline:'Slow roast.\nDrink real.',heroDesc:'Đà Lạt beans, hand-selected. Slow-roasted in small batches. Brewed with technique — not formula.',fromPrice:'45,000₫',ctaText:'See menu',loaderSub:'Specialty Coffee · Đà Lạt Origin',products:[{name:'Summit Espresso',note:'Single origin · house blend · 30ml',price:'45,000₫'},{name:'Đà Lạt Pour-over',note:'V60 · hand-brew · 200ml',price:'65,000₫'},{name:'Cappuccino Cream',note:'Double shot · full-fat fresh milk',price:'55,000₫'},{name:'Cold Brew 12h',note:'Slow cold-extracted · 300ml',price:'55,000₫'},{name:'Flat White',note:'Ristretto · micro-foam milk',price:'60,000₫'},{name:'Summit roasted beans',note:'250g bag · medium roast · brew at home',price:'180,000₫'}],tag:'Daily · 7:00 → 22:00'},
    {id:'stay',num:'05',name:'MERUVA Stay',shortName:'Stay',sub:'Summit Living · For Rent',tagline:'Main road studio for rent',desc:'9 self-contained studios at 654A Quang Trung, Gò Vấp. 17m² · 21m² · 24m². Early-bird offer available.',heroTagline:'Live well.\nFrom the summit.',heroDesc:'9 self-contained studios on Quang Trung main road, Gò Vấp. Compact design, full amenities. Early-bird deal — save 12,000,000₫ in your first year.',fromPrice:'From 5,500,000₫/month',ctaText:'Reserve a spot',loaderSub:'Summit Living · 654A Quang Trung · Gò Vấp',customSubPage:true,products:[]},
    {id:'card',num:'06',name:'MERUVA Card',shortName:'Card',sub:'Peak Silver · Membership',tagline:'Ecosystem membership card',desc:'One card — unlocks every MERUVA door and partner perks. Earn points, enjoy discounts, access exclusive events.',heroTagline:'One card.\nEvery door.',heroDesc:'MERUVA Card connects you with the entire ecosystem — from coffee to bakery, consulting, and all partner benefits.',fromPrice:'Free',ctaText:'Get your card',loaderSub:'Membership · Ecosystem-wide',products:[{name:'Summit Member',note:'Earn points · 5% off across all brands',price:'Free'},{name:'Gold Member',note:'10% off · priority booking · birthday gift',price:'500,000₫/year'},{name:'Peak Member',note:'15% off · private events · personal barista call',price:'1,500,000₫/year'},{name:'Gift Card',note:'Custom denomination · personalized card',price:'From 200,000₫'}],tag:'Lifetime · Ecosystem-wide'}
  ],

  partners: [
    {name:'Studio Vạn',cat:'Creative · Branding',eyebrow:'Creative Partner',desc:'Brand design and visual identity studio based in Ho Chi Minh City. Specializing in brand identity, packaging design, and creative content for lifestyle brands.',offers:[{icon:'✦',title:'Free 30-min brand consultation',note:'Exclusively for MERUVA Card members',tag:'Free'},{icon:'◈',title:'10% off design services',note:'Applies to all brand identity & packaging packages',tag:'−10%'},{icon:'▲',title:'Priority scheduling',note:'Peak Members get booked within 48h',tag:'Peak'}]},
    {name:'Atlas Coffee',cat:'Specialty Roaster',eyebrow:'Coffee Partner',desc:'Leading specialty roaster — the source of hand-selected beans for MERUVA Coffee. From farm to cup, every batch is fully traceable.',offers:[{icon:'✦',title:'Roastery tasting session',note:'Visit and taste fresh beans — book through MERUVA',tag:'Exclusive'},{icon:'◈',title:'8% off direct bean purchases',note:'For Gold & Peak members',tag:'−8%'},{icon:'▲',title:'Monthly roasting workshop',note:'Priority sign-up for MERUVA Card holders',tag:'Monthly'}]},
    {name:'Maison Lụa',cat:'Lifestyle · Decor',eyebrow:'Lifestyle Partner',desc:'A curated lifestyle space — from small furniture pieces and decor lights to workspace accessories. Modern Asian aesthetics, carefully selected.',offers:[{icon:'✦',title:'12% off all products',note:'For Gold & Peak members',tag:'−12%'},{icon:'◈',title:'Workspace decor consultation',note:'Bundled with MERUVA Service consulting packages',tag:'Bundle'},{icon:'▲',title:'Welcome kit gift',note:'Included when signing up as a new Peak Member',tag:'Gift'}]},
    {name:'Nội thất Mộc',cat:'Furniture · Wood',eyebrow:'Craft Partner',desc:'Artisan woodworking studio — FSC natural wood furniture made to order. From desks to bookshelves, every piece is a craft work.',offers:[{icon:'✦',title:'7% off custom orders',note:'Apply when presenting MERUVA Card at checkout',tag:'−7%'},{icon:'◈',title:'Free space design consultation',note:'1 session of 45 min with the lead craftsman',tag:'Free'},{icon:'▲',title:'Custom engraving on request',note:'Free laser engraving for Peak Members',tag:'Peak'}]},
    {name:'Florist Hạ',cat:'Floral · Event',eyebrow:'Floral Partner',desc:"Artisan fresh flower studio — emotion-led bouquets, event setups, regular desk flowers. No mass-produced arrangements. Every bouquet tells a story.",offers:[{icon:'✦',title:'10% off fresh flower orders',note:'For all MERUVA Card members',tag:'−10%'},{icon:'◈',title:'Regular desk flower subscription',note:'Weekly / monthly plans — extra 5% off for members',tag:'Subscription'},{icon:'▲',title:'MERUVA event floral setup',note:'Florist Hạ is the exclusive floral partner for MERUVA events',tag:'Exclusive'}]},
    {name:'Print House',cat:'Print · Stationery',eyebrow:'Print Partner',desc:'Professional print house — business cards, menus, packaging, premium stationery. Offset & digital printing, special materials, handcrafted finishing.',offers:[{icon:'✦',title:'10% off first print order',note:'For new members presenting MERUVA Card',tag:'−10%'},{icon:'◈',title:'Free template design',note:'For standard items (card, A5 menu, voucher)',tag:'Free'},{icon:'▲',title:'24h express delivery',note:'Production priority for Peak Members',tag:'Priority'}]},
    null, null, null, null
  ],

  floorData: {
    4:{label:'3rd Floor',tag:'FLOOR 3',desc:'Top floor · open view · less noise',rooms:[{n:'Room 301 · 21m²',d:'6,000,000₫ / month'},{n:'Room 302 · 17m²',d:'5,500,000₫ / month'},{n:'Room 303 · 24m²',d:'6,500,000₫ / month'}]},
    3:{label:'2nd Floor',tag:'FLOOR 2',desc:'Middle floor · balance of access and privacy',rooms:[{n:'Room 201 · 21m²',d:'6,000,000₫ / month'},{n:'Room 202 · 17m²',d:'5,500,000₫ / month'},{n:'Room 203 · 24m²',d:'6,500,000₫ / month'}]},
    2:{label:'1st Floor',tag:'FLOOR 1',desc:'Convenient access · great for active lifestyles',rooms:[{n:'Room 101 · 21m²',d:'6,000,000₫ / month'},{n:'Room 102 · 17m²',d:'5,500,000₫ / month'},{n:'Room 103 · 24m²',d:'6,500,000₫ / month'}]},
    1:{label:'Ground Floor',tag:'GROUND',desc:'Covered parking area · reserved for residents',rooms:[{n:'Parking area',d:'6 spots · covered · residents only'},{n:'Main entrance',d:'654A Quang Trung · Gò Vấp'}]}
  }
},

/* ════════════════════════════════════════
   日本語
   ════════════════════════════════════════ */
ja: {
  nav_home:'ホーム', nav_eco:'エコシステム', nav_story:'ストーリー', nav_partners:'パートナー', nav_contact:'お問い合わせ',
  hero_eyebrow:'パーソナル・エコシステム · ホーチミン市',
  hero_title1:'山頂から',
  hero_title_em:'私たちは仕える。',
  hero_subline:'"From the summit, we serve." — MERUVA · Est. 2026',
  hero_desc:'Binが日本から持ち帰った、本物のおもてなしの精神で作り上げたエコシステム。誇張なし。バズワードなし。ただ、誠実に。',
  hero_btn1:'エコシステムを探る', hero_btn2:'ストーリー',
  stat1_label:'ブランド', stat2_label:'個別コンサルティング', stat3_label:'日本語 · 国際的思考', stat4_label:'毎朝焼きたてのパン',
  eco_label:'エコシステム', eco_title1:'六つの枝。', eco_title2:'ひとつの精神。',
  eco_intro:'各サブブランドは、異なる方法で人々に奉仕します — 個人コンサルティング、3Dプリント、カフェ、アルチザンベーカリー、スタジオ賃貸、そしてエコシステム全体をつなぐメンバーシップカード。',
  eco_explore:'詳しく見る',
  story_label:'ストーリー', story_title1:'山頂は', story_title2:'眺めるため', story_title3:'だけにあらず。',
  story_desc1:'MERUVAは「メル」— アジア文化における聖なる山から着想を得ています。征服するためではなく、その頂から、人々に真に仕えるために。',
  story_desc2:'Binは5年間日本で奉仕の精神を観察して帰ってきました — <em style="color:var(--gold)">おもてなし</em>。多くを語らず。誠実に行動する。',
  val1_title:'Serve First', val1_desc:'売る前に仕える。すべての製品は親切な行為。',
  val2_title:'Summit Quality', val2_desc:'妥協しない。山頂に「まあまあ」の居場所はない。',
  val3_title:'Honest Craft', val3_desc:'食材、工程、価格すべてにおいて透明。虚飾なし。',
  card1_label:'ブランドタグライン', card1_quote:'"From the summit, we serve."',
  card2_label:'ビジョン', card2_quote:'"品質、誠実さ、そして本物のおもてなし精神で愛されるパーソナルエコシステム。"',
  card3_label:'ブランドパーソナリティ', card3_quote:'"28歳、留学帰り、国際基準を理解しながらもベトナムらしさを大切に。行動で語る。自然な笑顔。"',
  partners_label:'パートナーネットワーク', partners_title1:'共に築く', partners_title2:'エコシステム。',
  contact_label:'お問い合わせ', contact_title1:'誠実に', contact_title2:'話しましょう。',
  ci_hours_label:'営業時間', ci_hours_val:'毎日 · 7:00 → 22:00',
  form_name_label:'お名前', form_email_label:'メールアドレス', form_msg_label:'メッセージ',
  form_msg_ph:'MERUVAへの訪問・コラボレーション・相談予約...',
  form_submit:'メッセージを送る', form_thank:'ありがとうございます！MERUVAより近日中にご連絡します ☕',
  footer_eco:'エコシステム', footer_story:'ストーリー', footer_contact:'お問い合わせ', footer_copy:'© 2026 MERUVA · Brand Book v1.0',
  sp_back:'← 戻る', sp_from:'料金：', sp_products_label:'製品・サービス', sp_cta_suffix:' — 本物のサービスとともに。"',
  pm_offers_label:'MERUVAカード会員限定特典', pm_footer_note:'MERUVA · パートナーネットワーク', pm_cta:'パートナーに連絡 →', pm_detail:'詳細を見る ↗', coming_soon:'準備中',
  stay_eyebrow:'Summit Living · 654A Quang Trung, Gò Vấp',
  stay_title_em:'良く生きる。', stay_title2:'山頂から。',
  stay_coming:'完成予定 · 2026年9月',
  stay_desc:'クアントルン大通り沿い、ゴーバップの独立スタジオ。コンパクトな設計、充実した設備、優れたセキュリティ。3サイズのオプション。',
  stay_price_badge:'🏠 料金 · 3タイプ', stay_per_month:'/月',
  stay_early_bird:'✦ 2026年9月前に予約 — 特別早期割引特典',
  stay_cta:'今すぐ予約 →',
  stay_loc_label:'場所', stay_loc_val:'654A Quang Trung', stay_loc_sub:'Ward 11 · Gò Vấp · ホーチミン市',
  stay_type_label:'部屋タイプ', stay_type_val:'独立型スタジオ', stay_type_sub:'1ベッドルーム・キッチン・専用バスルーム',
  stay_area_label:'面積', stay_area_val:'17 · 21 · 24m²', stay_area_sub:'3タイプ · 合計9室',
  stay_rent_label:'家賃', stay_rent_val:'5,500,000₫〜', stay_rent_sub:'/月 · 3つの価格帯',
  stay_floor_label:'ビル構造', stay_floor_t1:'9スタジオ。', stay_floor_t2:'3フロア。',
  stay_floor_hint:'↓ 図をクリックして各フロアを探索',
  stay_types_label:'スタジオタイプ', stay_types_t1:'あなたに合った', stay_types_t2:'空間を選ぶ。',
  stay_popular:'人気', stay_rent_card:'月額家賃', stay_book_now:'予約する',
  roomA_name:'ルームA', roomA_li1:'ベッドルーム＋ミニキッチン＋専用バスルーム', roomA_li2:'コンパクトで機能的なレイアウト', roomA_li3:'1人・学生・社会人に最適', roomA_li4:'自然光の窓', roomA_avail:'3室 · 1F / 2F / 3F',
  roomB_name:'ルームB', roomB_li1:'ベッドルーム＋キッチン＋専用バスルーム', roomB_li2:'使いやすいサイズで充実した機能', roomB_li3:'1〜2人向け', roomB_li4:'ワークデスク・クローゼット完備', roomB_avail:'3室 · 1F / 2F / 3F',
  roomC_name:'ルームC', roomC_li1:'広めのベッドルーム＋キッチン＋専用バスルーム', roomC_li2:'最も開放感のあるレイアウト', roomC_li3:'カップル・1〜2人に最適', roomC_li4:'専用ワークコーナー・大型クローゼット', roomC_avail:'3室 · 1F / 2F / 3F',
  stay_amenities_label:'設備', stay_amenities_t1:'充実の設備。', stay_amenities_t2:'不足なし。',
  amenity1:'エアコン', amenity2:'温水シャワー', amenity3:'IH調理器', amenity4:'冷蔵庫', amenity5:'ベッド・マットレス', amenity6:'ワードローブ', amenity7:'ワークデスク', amenity8:'高速WiFi', amenity9:'セキュリティカメラ', amenity10:'駐車スペース',
  stay_loc_sec_label:'立地', stay_loc_t1:'大通り沿い。', stay_loc_t2:'移動に便利。',
  loc1_title:'クアントルン大通り沿い', loc1_desc:'654A, P.11, ゴーバップ — 主要道路沿い、見つけやすく、交通至便',
  loc2_title:'飲食・ショッピング至便', loc2_desc:'ゴーバップ市場、スーパー、多彩な飲食店が近く',
  loc3_title:'市内中心部へのアクセス良好', loc3_desc:'1区まで約20〜25分 · 12区、ビンタン、タンビンへ接続',
  loc4_title:'教育・医療施設が近い', loc4_desc:'ゴーバップ・ビンタン地区の学生・社会人に最適',
  loc5_title:'安全な住宅エリア', loc5_desc:'人口密集地域、建物カメラ、各部屋個別ロック',
  map_note:'Google マップ · 近日公開',
  stay_process_label:'ご入居の流れ', stay_process_t1:'5ステップで', stay_process_t2:'入居完了。',
  step1_t:'フォーム記入', step1_n:'下記予約フォームに情報をご入力ください',
  step2_t:'ご相談', step2_n:'MERUVAより24営業時間以内にご連絡',
  step3_t:'デポジット', step3_n:'1ヶ月分の家賃をデポジットとしてお預かり',
  step4_t:'契約締結', step4_n:'完成後に締結 · 2026年9月',
  step5_t:'ご入居', step5_n:'MERUVA Stayでの生活をスタート',
  stay_form_label:'ご予約', stay_form_t1:'情報をご入力ください。', stay_form_t2:'24時間以内にご連絡します。',
  sf_name:'お名前', sf_name_ph:'お名前', sf_phone:'電話番号 / Zalo', sf_phone_ph:'+84 912 345 678', sf_email:'メールアドレス',
  sf_room:'ご希望のスタジオタイプ', sf_room_default:'— タイプを選択 —',
  sf_room_opt1:'ルームA · 17m² · 5,500,000₫/月', sf_room_opt2:'ルームB · 21m² · 6,000,000₫/月', sf_room_opt3:'ルームC · 24m² · 6,500,000₫/月', sf_room_opt4:'未定 · 詳しく相談したい',
  sf_people:'入居人数', sf_people_default:'— 選択 —', sf_people_1:'1名', sf_people_2:'2名',
  sf_movein:'ご希望の入居時期', sf_movein_default:'— 選択 —',
  sf_movein_1:'2026年9月（最短）', sf_movein_2:'2026年10月', sf_movein_3:'2026年11月以降',
  sf_note:'備考', sf_note_ph:'特別なご要望、ご質問など...',
  sf_send:'予約を送信 →', sf_thank:'ご予約ありがとうございます！\nMERUVAより24時間以内にご連絡します ☕',
  stay_faq_label:'よくある質問', stay_faq_t1:'Q &', stay_faq_t2:'A。',
  faq1_q:'予約に必要なデポジットはいくらですか？', faq1_a:'1ヶ月分の家賃（5,500,000₫・6,000,000₫・または6,500,000₫、部屋タイプによる）をデポジットとしていただきます。このデポジットは最初の月の家賃に充当されます。入居日の30日前までにキャンセルの場合、100%全額返金いたします。',
  faq2_q:'工事が遅れた場合はどうなりますか？', faq2_a:'MERUVAはスケジュールに変更がある場合、早めにお知らせします。予約者は100%全額返金を受けるか、継続して待つかを選択できます — 追加費用は一切かかりません。',
  faq3_q:'ペットは飼えますか？', faq3_a:'MERUVA Stayは初期段階ではペット不可としています。ビルの運営開始後、入居者の意見をもとにポリシーが更新される可能性があります。',
  faq4_q:'長期契約は可能ですか？', faq4_a:'最低契約期間は3ヶ月です。6ヶ月契約で追加3%割引、1年契約で早期割引料金からさらに5%割引。最適なプランについてMERUVAにご相談ください。',
  faq5_q:'月払い・四半期払い・年払いはできますか？', faq5_a:'3つの支払いオプション全てに対応。月払い（通常）、四半期払いで追加3%割引、年払いで5%割引 — 早期予約料金に加算して適用されます。',

  ecosystem: [
    {id:'service',num:'01',name:'MERUVA Service',shortName:'Service',sub:'Trust Blue · Bespoke',tagline:'個人システムコンサルティング',desc:'Binが1対1で直接指導。思考からシステムへ — Notion、カレンダー、ワークフロー、自動化。セッションごとに山を登る一歩。',heroTagline:'システムを構築し、\n頂点へ。',heroDesc:'Binが個人システム・ワークフロー・自動化を1対1でコンサルティング。日本から持ち帰った思考をベトナムの現実に適用。テンプレートなし。コピペなし。',fromPrice:'300,000₫',ctaText:'セッションを予約',loaderSub:'Personal System · Bespoke · 1:1',products:[{name:'個人方向性コンサルティング',note:'60分 · キャリア＆ライフスタイル設計',price:'300,000₫'},{name:'個人システムコンサルティング',note:'1:1 · 90分 · オンライン/対面',price:'500,000₫'},{name:'個人ワークフローセットアップ',note:'Notion · カレンダー · 自動化 · フルセットアップ',price:'1,500,000₫'},{name:'法人プロジェクト',note:'スコープ見積もり · 直接お問い合わせ',price:'お問い合わせ'}],tag:'Bespoke · Made for you'},
    {id:'print3d',num:'02',name:'MERUVA 3D',shortName:'3D',sub:'Craft Series · Custom',tagline:'カスタム3Dプリント',desc:'デザインファイルから実物へ — PLA、PETG、レジン。キーホルダー、フィギュア、イベントグッズ、技術モデル。創造性に限界なし。',heroTagline:'デザインし、\nリアルにプリント。',heroDesc:'MERUVA 3Dがあなたのファイルを実物に変えます。プレミアムPLA、PETG、レジン。個人ギフトから企業イベントグッズまで — 3〜5日でお届け。',fromPrice:'80,000₫〜',ctaText:'注文する',loaderSub:'3D Printing · Custom · On-demand',products:[{name:'ファイルからの3Dプリント（PLA/PETG）',note:'STLファイルアップロード · 3〜5営業日でお届け',price:'150,000₫〜'},{name:'プレミアムレジンプリント',note:'シャープなディテール · 豊富なカラー',price:'250,000₫〜'},{name:'カスタムキーホルダー',note:'PLA · フルカラー · 大量注文対応',price:'80,000₫〜'},{name:'フィギュア＆モデル',note:'アニメ · キャラクター · バスト · 1:12スケール',price:'300,000₫〜'},{name:'イベントグッズ / コーポレートギフト',note:'カスタムロゴ · 個別パッケージ · 大量注文',price:'120,000₫〜'},{name:'法人プロジェクト',note:'技術試作品 · 量産 · スコープ見積もり',price:'お問い合わせ'}],tag:'On-demand · 3〜5日'},
    {id:'bakery',num:'03',name:'MERUVA Bakery',shortName:'Bakery',sub:'Cream Serve · Artisan',tagline:'毎朝焼きたてのパン',desc:'サクサクのクロワッサン、36時間発酵のサワードウ、アルチザンペイストリー。7時に焼き上げ — なくなり次第終了。温め直しなし。',heroTagline:'7時に焼き上げる。\nなくなり次第終了。',heroDesc:'温め直しなし。品質への妥協なし。すべてのパンは一つの約束 — フランスバター、全粒粉、天然酵母。',fromPrice:'45,000₫',ctaText:'パンを注文',loaderSub:'Artisan Bakery · Fresh Daily · 7:00',products:[{name:'バタークロワッサン',note:'フランスバター · サクサクの層 · 焼きたて',price:'45,000₫'},{name:'パン・オ・ショコラ',note:'ベルギー産70%チョコレート · 温かい',price:'55,000₫'},{name:'36時間サワードウ',note:'全粒粉 · 天然発酵 · 500gローフ',price:'120,000₫'},{name:'シナモンロール',note:'セイロンシナモン · クリームチーズフロスティング',price:'65,000₫'},{name:'クイニーアマン',note:'カリカリキャラメル · 塩バター',price:'70,000₫'},{name:'カスタムケーキ',note:'カスタムデザイン · 48時間前予約',price:'450,000₫〜'}],tag:'Fresh daily · なくなり次第終了'},
    {id:'coffee',num:'04',name:'MERUVA Coffee',shortName:'Coffee',sub:'Summit Gold · Specialty',tagline:'スペシャルティコーヒー',desc:'ダラットから手選びした豆を少量ずつスロースロースト。本格エスプレッソ、ゲストに合わせたプアオーバー。',heroTagline:'ゆっくり焙煎。\nリアルに飲む。',heroDesc:'ダラットの豆を手選び。小バッチでスローロースト。テクニックで淹れる — 公式ではなく。',fromPrice:'45,000₫',ctaText:'メニューを見る',loaderSub:'Specialty Coffee · Đà Lạt Origin',products:[{name:'サミットエスプレッソ',note:'シングルオリジン · ハウスブレンド · 30ml',price:'45,000₫'},{name:'ダラットプアオーバー',note:'V60 · ハンドブリュー · 200ml',price:'65,000₫'},{name:'カプチーノクリーム',note:'ダブルショット · 全脂新鮮牛乳',price:'55,000₫'},{name:'コールドブリュー12時間',note:'スローコールドエクストラクト · 300ml',price:'55,000₫'},{name:'フラットホワイト',note:'リストレット · マイクロフォームミルク',price:'60,000₫'},{name:'サミット焙煎豆',note:'250g袋 · ミディアムロースト · 自宅用',price:'180,000₫'}],tag:'毎日 · 7:00 → 22:00'},
    {id:'stay',num:'05',name:'MERUVA Stay',shortName:'Stay',sub:'Summit Living · For Rent',tagline:'大通り沿いスタジオ賃貸',desc:'654A Quang Trung, Gò Vấpに9室の独立スタジオ。17m² · 21m² · 24m²。早期予約特典あり。',heroTagline:'良く生きる。\n山頂から。',heroDesc:'ゴーバップのクアントルン大通り沿いに9室の独立スタジオ。コンパクト設計、充実設備。早期予約で12,000,000₫お得。',fromPrice:'5,500,000₫/月〜',ctaText:'今すぐ予約',loaderSub:'Summit Living · 654A Quang Trung · Gò Vấp',customSubPage:true,products:[]},
    {id:'card',num:'06',name:'MERUVA Card',shortName:'Card',sub:'Peak Silver · Membership',tagline:'エコシステム会員カード',desc:'1枚のカード — MERUVAとパートナーすべてのドアを開く。ポイント獲得、割引、限定イベント。',heroTagline:'1枚のカード。\nすべてのドア。',heroDesc:'MERUVAカードでエコシステム全体とつながる — コーヒーからベーカリー、コンサルティング、すべてのパートナー特典まで。',fromPrice:'無料',ctaText:'カードを取得',loaderSub:'Membership · Ecosystem-wide',products:[{name:'サミットメンバー',note:'ポイント獲得 · 全ブランド5%割引',price:'無料'},{name:'ゴールドメンバー',note:'10%割引 · 予約優先 · 誕生日ギフト',price:'500,000₫/年'},{name:'ピークメンバー',note:'15%割引 · 限定イベント · 専属バリスタコール',price:'1,500,000₫/年'},{name:'ギフトカード',note:'金額選択可 · 名入れカード',price:'200,000₫〜'}],tag:'Lifetime · Ecosystem-wide'}
  ],

  partners: [
    {name:'Studio Vạn',cat:'Creative · Branding',eyebrow:'クリエイティブパートナー',desc:'ホーチミン市のブランドデザイン・ビジュアルアイデンティティスタジオ。ライフスタイルブランドのブランドアイデンティティ、パッケージデザイン、クリエイティブコンテンツを専門とする。',offers:[{icon:'✦',title:'30分無料ブランドコンサルティング',note:'MERUVAカード会員限定',tag:'無料'},{icon:'◈',title:'デザインサービス10%割引',note:'全ブランドアイデンティティ・パッケージに適用',tag:'−10%'},{icon:'▲',title:'スケジュール優先対応',note:'ピークメンバーは48時間以内に予約確定',tag:'Peak'}]},
    {name:'Atlas Coffee',cat:'Specialty Roaster',eyebrow:'コーヒーパートナー',desc:'一流スペシャルティロースター — MERUVAコーヒーに豆を提供。ファームからカップまで、すべてのバッチがトレーサブル。',offers:[{icon:'✦',title:'ロースタリーテイスティングセッション',note:'見学と新鮮な豆の試飲 — MERUVA経由で予約',tag:'限定'},{icon:'◈',title:'直接豆購入8%割引',note:'ゴールド＆ピークメンバー対象',tag:'−8%'},{icon:'▲',title:'月次焙煎ワークショップ',note:'MERUVAカード保持者優先申込',tag:'Monthly'}]},
    {name:'Maison Lụa',cat:'Lifestyle · Decor',eyebrow:'ライフスタイルパートナー',desc:'キュレーテッドライフスタイル空間 — 小家具からデコライト、ワークスペースアクセサリーまで。モダンアジアの美学を丁寧に選び抜く。',offers:[{icon:'✦',title:'全商品12%割引',note:'ゴールド＆ピークメンバー対象',tag:'−12%'},{icon:'◈',title:'ワークスペースデココンサルティング',note:'MERUVAサービスのコンサルティングパッケージとバンドル',tag:'Bundle'},{icon:'▲',title:'ウェルカムキットプレゼント',note:'新ピークメンバー登録時に贈呈',tag:'Gift'}]},
    {name:'Nội thất Mộc',cat:'Furniture · Wood',eyebrow:'クラフトパートナー',desc:'職人木工スタジオ — FSC認証天然木のオーダーメイド家具。デスクから本棚まで、すべての作品が一点もの。',offers:[{icon:'✦',title:'カスタムオーダー7%割引',note:'注文時にMERUVAカードを提示',tag:'−7%'},{icon:'◈',title:'空間デザイン無料コンサルティング',note:'主任職人との45分コンサルティング1回',tag:'無料'},{icon:'▲',title:'名前/ロゴのカスタム刻印',note:'ピークメンバーはレーザー刻印無料',tag:'Peak'}]},
    {name:'Florist Hạ',cat:'Floral · Event',eyebrow:'フローラルパートナー',desc:'アルチザン生花スタジオ — 感情に基づいたブーケ、イベントセットアップ、定期デスクフラワー。量産アレンジメントなし。すべてのブーケが物語を持つ。',offers:[{icon:'✦',title:'生花注文10%割引',note:'MERUVAカード会員全員に適用',tag:'−10%'},{icon:'◈',title:'定期デスクフラワーサブスクリプション',note:'週次/月次プラン — 会員さらに5%割引',tag:'定期'},{icon:'▲',title:'MERUVAイベントフローラルセットアップ',note:'Florist HạはMERUVAイベントの独占フローラルパートナー',tag:'限定'}]},
    {name:'Print House',cat:'Print · Stationery',eyebrow:'プリントパートナー',desc:'プロフェッショナル印刷会社 — 名刺、メニュー、パッケージ、プレミアム文具。オフセット＆デジタル印刷、特殊素材、手作業仕上げ。',offers:[{icon:'✦',title:'初回印刷注文10%割引',note:'MERUVAカードを提示する新会員対象',tag:'−10%'},{icon:'◈',title:'テンプレートデザイン無料',note:'標準印刷物（名刺、A5メニュー、バウチャー）',tag:'無料'},{icon:'▲',title:'24時間エクスプレス配送',note:'ピークメンバー優先製造',tag:'優先'}]},
    null, null, null, null
  ],

  floorData: {
    4:{label:'3階',tag:'3階',desc:'最上階 · 開けた眺め · 静か',rooms:[{n:'301号室 · 21m²',d:'6,000,000₫ / 月'},{n:'302号室 · 17m²',d:'5,500,000₫ / 月'},{n:'303号室 · 24m²',d:'6,500,000₫ / 月'}]},
    3:{label:'2階',tag:'2階',desc:'中間フロア · アクセスとプライバシーのバランス',rooms:[{n:'201号室 · 21m²',d:'6,000,000₫ / 月'},{n:'202号室 · 17m²',d:'5,500,000₫ / 月'},{n:'203号室 · 24m²',d:'6,500,000₫ / 月'}]},
    2:{label:'1階',tag:'1階',desc:'アクセス便利 · アクティブなライフスタイルに最適',rooms:[{n:'101号室 · 21m²',d:'6,000,000₫ / 月'},{n:'102号室 · 17m²',d:'5,500,000₫ / 月'},{n:'103号室 · 24m²',d:'6,500,000₫ / 月'}]},
    1:{label:'1F（駐車場）',tag:'駐車場',desc:'屋根付き駐車エリア · 入居者専用',rooms:[{n:'駐車エリア',d:'6スポット · 屋根付き · 入居者専用'},{n:'メインエントランス',d:'654A Quang Trung · Gò Vấp'}]}
  }
}

}; /* end MERUVA_LANG */
